MERGE INTO dbo.controller AS target
USING #temp_controller AS source
ON target.record_hash = source.record_hash
WHEN NOT MATCHED THEN
    INSERT (controller_name,
            controller_description,
            catalog_number,
            revision,
            project_creation_date,
            last_modified_date,
            communication_path,
            sfc_execution_control,
            sfc_restart_position,
            sfc_last_scan,
            project_serial_number,
            match_project_to_controller,
            inhibit_firmware_updates,
            allow_rfi_from_producer,
            pass_through_option,
            download_documentation,
            download_properties,
            ethernet_ip_mode,
            redundancy_enabled,
            keep_test_edits_on_switch,
            io_memory_pad_percent,
            data_table_pad_percent,
            safety_signature,
            safety_lock_password,
            safety_unlock_password,
            configure_safety_io_always,
            signature_run_mode_protect,
            security_code,
            security_authority_id,
            security_authority_uri,
            permission_set,
            changed_to_detect,
            trusted_slots,
            record_hash)
    VALUES (source.controller_name,
            source.controller_description,
            source.catalog_number,
            source.revision,
            source.project_creation_date,
            source.last_modified_date,
            source.communication_path,
            source.sfc_execution_control,
            source.sfc_restart_position,
            source.sfc_last_scan,
            source.project_serial_number,
            source.match_project_to_controller,
            source.inhibit_firmware_updates,
            source.allow_rfi_from_producer,
            source.pass_through_option,
            source.download_documentation,
            source.download_properties,
            source.ethernet_ip_mode,
            source.redundancy_enabled,
            source.keep_test_edits_on_switch,
            source.io_memory_pad_percent,
            source.data_table_pad_percent,
            source.safety_signature,
            source.safety_lock_password,
            source.safety_unlock_password,
            source.configure_safety_io_always,
            source.signature_run_mode_protect,
            source.security_code,
            source.security_authority_id,
            source.security_authority_uri,
            source.permission_set,
            source.changed_to_detect,
            source.trusted_slots,
            source.record_hash);

INSERT INTO dbo.target_version_map (version_id, record_id, component_id)
SELECT @VersionId,
       (SELECT controller_id FROM dbo.controller WHERE record_hash = t.record_hash),
       (SELECT component_id FROM dbo.component WHERE component_name = 'controller')
FROM #temp_controller t;
