using L5Sharp.Core;
using LogixDb.Data.Abstractions;
using LogixDb.Data.Maps;
using Task = System.Threading.Tasks.Task;

namespace LogixDb.Data.Sqlite.Imports;

/// <summary>
/// Handles the import of tag records from a LogixDb snapshot into an SQLite database.
/// This class processes tag entities by querying them from the snapshot source and inserting
/// them into the database using the configured tag table mapping.
/// </summary>
internal class SqliteTagImport : SqliteImport
{
    private readonly TagMap _tagMap = new();
    private readonly TagCommentMap _commentMap = new();
    private readonly TagProduceInfoMap _produceInfoMap = new();

    /// <inheritdoc />
    public override async Task Process(Snapshot snapshot, ILogixDbSession session, ImportOptions options,
        CancellationToken token)
    {
        var source = snapshot.GetSource();
        var tagRecords = new List<TagRecord>();
        var commentRecords = new List<TagCommentRecord>();
        var producrRecords = new List<TagProduceInfoRecord>();
        //produce
        //consume

        var tags = source.Query<Tag>().SelectMany(t => t.Members());

        foreach (var tag in tags)
        {
            var snapshotId = snapshot.SnapshotId;
            var tagRecord = new TagRecord(snapshotId, tag);
            var tagId = tagRecord.TagId;
            var tagName = tag.TagName.LocalPath;

            tagRecords.Add(tagRecord);
            commentRecords.AddRange(GetTagComments(tag, snapshotId, tagId, tagName));

            if (tag.ProduceInfo is not null)
            {
                producrRecords.Add(new TagProduceInfoRecord(snapshotId, tagId, tag.ProduceInfo));
            }
        }

        await ImportRecords(tagRecords, _tagMap, session, token);
        await ImportRecords(commentRecords, _commentMap, session, token);
        await ImportRecords(producrRecords, _produceInfoMap, session, token);
    }

    /// <summary>
    /// Retrieves a collection of tag comment records based on the provided tag's description and comments.
    /// If the tag contains a description, it will be included as a comment record.
    /// For tags with bit-level comments, additional comment records are generated by combining the base tag name with the bit-level comment operand.
    /// </summary>
    /// <param name="tag">The tag object containing description and comments.</param>
    /// <param name="snapshotId">The unique identifier of the snapshot containing the tag.</param>
    /// <param name="tagId">The unique identifier of the tag.</param>
    /// <param name="baseName">The base name of the tag used for constructing bit-level tag names.</param>
    /// <returns>A collection of <see cref="TagCommentRecord">TagCommentRecord</see> instances representing the tag's comments.</returns>
    private static IEnumerable<TagCommentRecord> GetTagComments(Tag tag, int snapshotId, Guid tagId, string baseName)
    {
        if (tag.Description is not null)
            yield return new TagCommentRecord(snapshotId, tagId, baseName, tag.Description);

        if (tag.Comments is null)
            yield break;

        // We need to get all bit level comments of this tag.
        foreach (var comment in tag.Comments)
        {
            if (comment.Operand.Contains(tag.TagName.Operand) && comment.Operand.Element.All(char.IsDigit))
            {
                var bitTag = TagName.Combine(baseName, comment.Operand);
                //the comment should mimic pass through descriptions like base-description does. Maybe this is something we can update on L5Sharp
                var text = string.Concat(tag.Description, " ", comment.Value);
                yield return new TagCommentRecord(snapshotId, tagId, bitTag, text);
            }
        }
    }
}