INSERT INTO controller (controller_name,
                         controller_description,
                         catalog_number,
                         revision,
                         project_creation_date,
                         last_modified_date,
                         communication_path,
                         sfc_execution_control,
                         sfc_restart_position,
                         sfc_last_scan,
                         project_serial_number,
                         match_project_to_controller,
                         inhibit_firmware_updates,
                         allow_rfi_from_producer,
                         pass_through_option,
                         download_documentation,
                         download_properties,
                         ethernet_ip_mode,
                         redundancy_enabled,
                         keep_test_edits_on_switch,
                         io_memory_pad_percent,
                         data_table_pad_percent,
                         safety_signature,
                         safety_lock_password,
                         safety_unlock_password,
                         configure_safety_io_always,
                         signature_run_mode_protect,
                         security_code,
                         security_authority_id,
                         security_authority_uri,
                         permission_set,
                         changed_to_detect,
                         trusted_slots,
                         record_hash)
SELECT t.controller_name,
       t.controller_description,
       t.catalog_number,
       t.revision,
       t.project_creation_date,
       t.last_modified_date,
       t.communication_path,
       t.sfc_execution_control,
       t.sfc_restart_position,
       t.sfc_last_scan,
       t.project_serial_number,
       t.match_project_to_controller,
       t.inhibit_firmware_updates,
       t.allow_rfi_from_producer,
       t.pass_through_option,
       t.download_documentation,
       t.download_properties,
       t.ethernet_ip_mode,
       t.redundancy_enabled,
       t.keep_test_edits_on_switch,
       t.io_memory_pad_percent,
       t.data_table_pad_percent,
       t.safety_signature,
       t.safety_lock_password,
       t.safety_unlock_password,
       t.configure_safety_io_always,
       t.signature_run_mode_protect,
       t.security_code,
       t.security_authority_id,
       t.security_authority_uri,
       t.permission_set,
       t.changed_to_detect,
       t.trusted_slots,
       t.record_hash
FROM temp_controller t
ON CONFLICT (record_hash) DO NOTHING;

INSERT INTO target_version_map (version_id, record_id, component_id)
SELECT @VersionId,
       (SELECT controller_id FROM controller WHERE record_hash = t.record_hash),
       (SELECT component_id FROM component WHERE component_name = 'controller')
FROM temp_controller t;
