INSERT OR IGNORE INTO data_type_member (type_id,
                                        member_name,
                                        member_description,
                                        member_index,
                                        data_type,
                                        dimensions,
                                        radix,
                                        external_access,
                                        is_hidden,
                                        target_name,
                                        bit_number,
                                        record_hash)
SELECT (SELECT type_id FROM data_type WHERE record_hash = type_hash),
       member_name,
       member_description,
       member_index,
       data_type,
       dimensions,
       radix,
       external_access,
       is_hidden,
       target_name,
       bit_number,
       record_hash
FROM temp_data_type_member t;
