INSERT OR IGNORE INTO aoi_parameter (aoi_id,
                           parameter_name,
                           parameter_description,
                           data_type,
                           dimensions,
                           radix,
                           default_value,
                           external_access,
                           tag_usage,
                           tag_type,
                           tag_alias,
                           is_visible,
                           is_required,
                           is_constant,
                           record_hash)
SELECT (SELECT aoi_id FROM aoi WHERE record_hash = t.aoi_id),
       t.parameter_name,
       t.parameter_description,
       t.data_type,
       t.dimensions,
       t.radix,
       t.default_value,
       t.external_access,
       t.tag_usage,
       t.tag_type,
       t.tag_alias,
       t.is_visible,
       t.is_required,
       t.is_constant,
       t.record_hash
FROM temp_aoi_parameter t;
